# Pipeline configuration

# --- Organism to restrict search to
organism: "Haemonchus"

# ---- Marker gene to search.  Currently ITS2 and 18S are supported
marker: "ITS2"

# --- Output directory
out_directory: "test"

# --- Database version
version: 0.0.1

# --- Database title
title: "Test"

# --- Marker specific parameters
# set according to the expected length of the marker you are searching
# Recommended values:
# ITS2: max_width: 700 and min_width: 100
# 18S: max_width: 2000 and min_width: 400
max_width: 700
min_width: 100

# --- Should untrimmed sequences be returned.  Valid only for ITS2
return_untrimmed: TRUE

# --- Download NCBI taxonomy database
download_taxdb: TRUE
delete_taxdb: FALSE

# --- General
ncbi_api: ""
threads: 10
